#http://play-with-docker.com/?stack=https://raw.githubusercontent.com/petehalverson/docker-octobercms-examples/master/stack-redis.yml
version: '3.3'
services:
  web:
    image: aspendigital/octobercms:latest
    ports:
      - 80:80
    environment:
      - CACHE_STORE=redis
      - DB_DATABASE=octobercms
      - DB_HOST=mysql
      - DB_PASSWORD=root
      - DB_TYPE=mysql
      - DB_USERNAME=root
      - INIT_OCTOBER=true
      - QUEUE_DRIVER=redis
      - SESSION_DRIVER=redis
    deploy:
      replicas: 3

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=octobercms

  redis:
    image: redis:5
