version: '2.2'
services:
  web:
    image: aspendigital/octobercms:latest
    init: true
    ports:
      - 80:80
    environment:
      - TZ=${TZ:-America/Denver}

  mysql:
    image: mysql:latest
    init: true
    ports:
      - 3306:3306
    environment:
      - TZ=${TZ:-America/Denver}
      - MYSQL_ROOT_PASSWORD=root
