version: '2.2'
services:
  web:
    image: aspendigital/octobercms:latest
    init: true
    ports:
      - 80:80
    environment:
      - TZ=${TZ:-America/Denver}
    volumes:
      - ./.env:/var/www/html/.env
      - ./config/docker:/var/www/html/config/docker
      - ./plugins:/var/www/html/plugins
      - ./storage/app:/var/www/html/storage/app
      - ./storage/logs:/var/www/html/storage/logs
      - ./themes:/var/www/html/themes

  mysql:
    image: mysql:latest
    init: true
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - TZ=${TZ:-America/Denver}
    volumes:
      - .docker/mysql/export.sh:/export.sh
      - .docker/mysql/store:/var/lib/mysql
      - .docker/mysql/imports:/docker-entrypoint-initdb.d
      - .docker/mysql/exports:/exports
